Fix/fix two player graph class
aria-systems-group/regret_synthesis_toolbox pull request #4
Opened 2022-04-25 03:12 UTC by MuvvalaKaran

2022-04-25 03:13 UTC, MuvvalaKaran commented
Hey, 

I also fixed a bug in DFA construction and reopened the pull request.

2022-06-20 16:47 UTC, watakandai requested changes

2022-06-20 16:47 UTC, watakandai commented on src/graph/two_player_graph.py
> +        self._instance._graph = nx.MultiDiGraph(name=graph_name)
NEVER ACCESS PRIVATE VARIABLES OUTSIDE A CLASS. 
`self._instance._graph = nx.MultiDiGraph(name=graph_name)` is already taken care of inside the constructor of `TwoPlayerGraph`

2022-06-20 16:47 UTC, watakandai commented on src/graph/product.py
> +                                                                                    # pref=pref)
same here.

2022-06-20 16:47 UTC, watakandai commented on src/graph/dfa.py
> +            if _s.startswith("accept"):
For now, I think this is fine. In the future, we should keep the constant parameters INIT and ACCEPT in one place and use them to check these lines.

2022-08-01 23:57 UTC, MuvvalaKaran commented
Updated the PR. Fixed Private variable issue

2022-08-02 01:26 UTC, watakandai approved these changes

2022-08-02 01:35 UTC, merged